### ISSUE TITLE
Missing encode.py 

### ISSUE THREAD

**Issue by hexnov** [NVISOsecurity/codasm#1]
In the README and your presentation, there is a `encode.py` file that is missing in this repository.
Is this intended, did I misunderstand something here, or did it maybe get lost?
Thanks in advance!

**Comment by molatho** [comment]
Hi, thanks for reporting this and sorry for the late reply. This was a leftover of a major refactoring I did on the codebase during which I renamed `encode.py` to `codasm.py`. I updated the README accordingly. Hope this helps!
